### ISSUE TITLE
Filters are not escaped

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-fulltextsearch#269] opened 2019-11-07 22:33 UTC
https://github.com/silverstripe/silverstripe-fulltextsearch/blob/6c59fcfdf0f19f25e6a298854af06235afdc9440/src/Solr/SolrIndex.php#L1044-L1047

Filters added to a search query are _not_ sanitised
Exclusions added to a search query _are_ sanitised

This is confusing and not a good experience, as a developer must escape some classnames and no others when consuming the API to perform a search.

**Comment by emteknetnz** [comment] 2020-04-03 01:46
This should be fairly easy, 
```
public function sanitiseClassName($className, $replaceWith = '\\\\')
    {
        return str_replace('\\', $replaceWith, $className);
    }
```
Update this to detect if there's any double escaping about to happen, to prevent break existing sites that are adding ->sanitiseClassName in their custom code e.g. https://github.com/silverstripe/silverstripe-fulltextsearch/issues/247#issuecomment-479696911

Then just add $this->sanitiseClassName() to getRequireFiltersComponent()

**Comment by dhensby** [comment] 2020-04-03 10:20
This is a duplicate of #247

**Closed by dhensby** 2020-04-03 10:20 UTC
Labels: affects/v4, effort/easy, impact/medium, type/bug
